from .tools import *

tool_defs = {
    'AutoInsightsUploader': None, # AutoInsightsUploader, 
    'AlteryxBasePluginsGui.BrowseV2.BrowseV2': None, # Browse, 
    'DateTimeNow': None, # DateTimeNow, 
    'AlteryxBasePluginsGui.Directory.Directory': None, # Directory, 
    'AlteryxBasePluginsGui.DbFileInput.DbFileInput': InputData, 
    'AlteryxSpatialPluginsGui.MapInput.MapInput': None, # MapInput, 
    'AlteryxBasePluginsGui.DbFileOutput.DbFileOutput': None, # OutputData, 
    'AlteryxBasePluginsGui.TextInput.TextInput': None, # TextInput, 
    'AlteryxBasePluginsGui.AutoField.AutoField': None, # AutoField, 
    'Predictive Tools\\Create_Samples.yxmc': None, # CreateSamples, 
    'Cleanse.yxmc': None, # DataCleansing, 
    'AlteryxBasePluginsGui.Filter.Filter': Filter, 
    'AlteryxBasePluginsGui.Formula.Formula': None, # Formula, 
    'AlteryxBasePluginsGui.GenerateRows.GenerateRows': None, # GenerateRows, 
    'Imputation_v3.yxmc': None, # Imputation, 
    'MultiFieldBinning_v2.yxmc': None, # MultiFieldBinning, 
    'AlteryxBasePluginsGui.MultiFieldFormula.MultiFieldFormula': None, # MultiFieldFormula, 
    'AlteryxBasePluginsGui.MultiRowFormula.MultiRowFormula': None, # MultiRowFormula, 
    'Predictive Tools\\Oversample_Field.yxmc': None, # OversampleField, 
    'RandomRecords.yxmc': None, # Random%Sample, 
    'AlteryxBasePluginsGui.RecordID.RecordID': None, # RecordID, 
    'AlteryxBasePluginsGui.Sample.Sample': None, # Sample, 
    'AlteryxBasePluginsGui.AlteryxSelect.AlteryxSelect': Select, 
    'SelectRecords.yxmc': None, # SelectRecords, 
    'AlteryxBasePluginsGui.Sort.Sort': Sort, 
    'AlteryxBasePluginsGui.Tile.Tile': None, # Tile, 
    'AlteryxBasePluginsGui.Unique.Unique': None, # Unique, 
    'AlteryxBasePluginsGui.AppendFields.AppendFields': None, # AppendFields, 
    'AlteryxBasePluginsGui.FindReplace.FindReplace': None, # FindReplace, 
    'AlteryxBasePluginsGui.FuzzyMatch.FuzzyMatch': None, # FuzzyMatch, 
    'AlteryxBasePluginsGui.Join.Join': Join, 
    'AlteryxBasePluginsGui.JoinMultiple.JoinMultiple': None, # JoinMultiple, 
    'AlteryxBasePluginsGui.MakeGroup.MakeGroup': None, # MakeGroup, 
    'AlteryxBasePluginsGui.Union.Union': Union, 
    'AlteryxBasePluginsGui.DateTime.DateTime': None, # DateTime, 
    'AlteryxBasePluginsGui.RegEx.RegEx': None, # RegEx, 
    'AlteryxBasePluginsGui.TextToColumns.TextToColumns': None, # TextToColumns, 
    'AlteryxBasePluginsGui.XMLParse.XMLParse': None, # XMLParse, 
    'AlteryxBasePluginsGui.Arrange.Arrange': None, # Arrange, 
    'CountRecords.yxmc': None, # CountRecords, 
    'AlteryxBasePluginsGui.CrossTab.CrossTab': None, # CrossTab, 
    'AlteryxBasePluginsGui.MakeColumns.MakeColumns': None, # MakeColumns, 
    'AlteryxBasePluginsGui.RunningTotal.RunningTotal': None, # RunningTotal, 
    'AlteryxSpatialPluginsGui.Summarize.Summarize': None, # Summarize, 
    'AlteryxBasePluginsGui.Transpose.Transpose': None, # Transpose, 
    'WeightedAvg.yxmc': None, # WeightedAverage, 
    'LockInGui.LockInBrowse.LockInBrowse': None, # BrowseInDB, 
    'LockInGui.LockInInput.LockInInput': None, # ConnectInDB, 
    'LockInGui.LockInStreamIn.LockInStreamIn': None, # DataStreamIn, 
    'LockInGui.LockInStreamOut.LockInStreamOut': None, # DataStreamOut, 
    'LockInGui.LockInDynamicInput.LockInDynamicInput': None, # DynamicInputInDB, 
    'LockInGui.LockInDynamicOutput.LockInDynamicOutput': None, # DynamicOutputInDB, 
    'LockInGui.LockInFilter.LockInFilter': None, # FilterInDB, 
    'LockInGui.LockInFormula.LockInFormula': None, # FormulaInDB, 
    'LockInGui.LockInJoin.LockInJoin': None, # JoinInDB, 
    'LockInGui.LockInMacroInput.LockInMacroInput': None, # MacroInputInDB, 
    'LockInGui.LockInMacroOutput.LockInMacroOutput': None, # MacroOutputInDB, 
    'LockInGui.LockInSample.LockInSample': None, # SampleInDB, 
    'LockInGui.LockInSelect.LockInSelect': None, # SelectInDB, 
    'LockInGui.LockInSummarize.LockInSummarize': None, # SummarizeInDB, 
    'LockInGui.LockInUnion.LockInUnion': None, # UnionInDB, 
    'LockInGui.LockInOutput.LockInOutput': None, # WriteDataInDB, 
    'PortfolioPluginsGui.Email.Email': None, # Email, 
    'PortfolioPluginsGui.ComposerImage.PortfolioComposerImage': None, # Image, 
    'Insights': None, # Insight, 
    'PlotlyCharting': None, # InteractiveChart, 
    'PortfolioPluginsGui.ComposerLayout.PortfolioComposerLayout': None, # Layout, 
    'Legend_Builder.yxmc': None, # MapLegendBuilder, 
    'Legend_Splitter.yxmc': None, # MapLegendSplitter, 
    'PortfolioPluginsGui.ComposerOverlay.Overlay': None, # Overlay, 
    'PortfolioPluginsGui.ComposerRender.PortfolioComposerRender': None, # Render, 
    'FooterMacro.yxmc': None, # ReportFooter, 
    'ReportHeader': None, # ReportHeader, 
    'AlteryxSpatialPluginsGui.ReportMap.ReportMap': None, # ReportMap, 
    'PortfolioPluginsGui.ComposerText.PortfolioComposerText': None, # ReportText, 
    'PortfolioPluginsGui.ComposerTable.PortfolioComposerTable': None, # Table, 
    'AlteryxGuiToolkit.TextBox.TextBox': Comment, 
    'AlteryxGuiToolkit.HtmlBox.HtmlBox': None, # ExplorerBox, 
    'AlteryxGuiToolkit.ToolContainer.ToolContainer': None, # ToolContainer, 
    'AlteryxSpatialPluginsGui.Buffer.Buffer': None, # Buffer, 
    'AlteryxSpatialPluginsGui.CreatePoints.CreatePoints': None, # CreatePoints, 
    'AlteryxSpatialPluginsGui.Distance.Distance': None, # Distance, 
    'AlteryxSpatialPluginsGui.FindNearest.FindNearest': None, # FindNearest, 
    'AlteryxSpatialPluginsGui.Generalize.Generalize': None, # Generalize, 
    'HeatMap.yxmc': None, # HeatMap, 
    'AlteryxSpatialPluginsGui.MakeGrid.MakeGrid': None, # MakeGrid, 
    'Non_Overlapping_DT.yxmc': None, # NonOverlapDrivetime, 
    'AlteryxSpatialPluginsGui.PolyBuild.PolyBuild': None, # PolyBuild, 
    'AlteryxSpatialPluginsGui.PolySplit.PolySplit': None, # PolySplit, 
    'AlteryxSpatialPluginsGui.Smooth.Smooth': None, # Smooth, 
    'AlteryxSpatialPluginsGui.SpatialInfo.SpatialInfo': None, # SpatialInfo, 
    'AlteryxSpatialPluginsGui.SpatialMatch.SpatialMatch': None, # SpatialMatch, 
    'AlteryxSpatialPluginsGui.SpatialProcess.SpatialProcess': None, # SpatialProcess, 
    'AlteryxSpatialPluginsGui.TradeArea.TradeArea': None, # TradeArea, 
    'AlteryxGuiToolkit.Action.Action': None, # Action, 
    'AlteryxGuiToolkit.Questions.CheckBoxGroup.CheckBoxGroup': None, # CheckBox, 
    'AlteryxGuiToolkit.Condition.Condition': None, # Condition, 
    'AlteryxGuiToolkit.Questions.ControlParam.ControlParam': None, # ControlParameter, 
    'AlteryxGuiToolkit.Questions.Date.Date': None, # Date, 
    'AlteryxGuiToolkit.Questions.DcmConnection.QuestionDcmConnection': None, # DCMConnection, 
    'AlteryxGuiToolkit.Questions.DropDownListBox.DropDown': None, # DropDown, 
    'AlteryxGuiToolkit.Error.Error': None, # ErrorMessage, 
    'AlteryxGuiToolkit.Questions.FileBrowse.FileBrowse': None, # FileBrowse, 
    'AlteryxGuiToolkit.Questions.FolderBrowse.FolderBrowse': None, # FolderBrowse, 
    'AlteryxGuiToolkit.Questions.DropDownListBox.ListBox': None, # ListBox, 
    'AlteryxBasePluginsGui.MacroInput.MacroInput': None, # MacroInput, 
    'AlteryxBasePluginsGui.MacroOutput.MacroOutput': None, # MacroOutput, 
    'AlteryxGuiToolkit.Questions.Map.Map': None, # Map, 
    'AlteryxGuiToolkit.Questions.NumericUpDown.NumericUpDown': None, # NumericUpDown, 
    'AlteryxGuiToolkit.Questions.RadioButtonGroup.RadioButtonGroup': None, # RadioButton, 
    'AlteryxGuiToolkit.Questions.TextBox.QuestionTextBox': None, # TextBox, 
    'AlteryxGuiToolkit.Questions.Tree.Tree': None, # Tree, 
    'Predictive Tools\\Association_Analysis.yxmc': None, # AssociationAnalysis, 
    'AlteryxBasePluginsGui.BasicDataProfile.BasicDataProfile': None, # BasicDataProfile, 
    'Predictive Tools\\ContingencyTable.yxmc': None, # ContingencyTable, 
    'Predictive Tools\\Distribution_Analysis.yxmc': None, # DistributionAnalysis, 
    'Predictive Tools\\Field_Summary_Report.yxmc': None, # FieldSummary, 
    'Predictive Tools\\Frequency.yxmc': None, # FrequencyTable, 
    'Predictive Tools\\Heat_Plot.yxmc': None, # HeatPlot, 
    'Importance Weights.yxmc': None, # ImportanceWeights, 
    'AlteryxBasePluginsGui.PearsonCorrelation.PearsonCorrelation': None, # PearsonCorrelation, 
    'Predictive Tools\\Plot_of_Means.yxmc': None, # PlotofMeans, 
    'SpearmanCorrCoeff.yxmc': None, # SpearmanCorrelation, 
    'Predictive Tools\\Violin_Plot.yxmc': None, # ViolinPlot, 
    'Predictive Tools\\Boosted_Model.yxmc': None, # BoostedModel, 
    'Predictive Tools\\Count_Regression.yxmc': None, # CountRegression, 
    'CrossValidation': None, # CrossValidation, 
    'DataRobotModelFactory': None, # DataRobotAutomodel, 
    'DataRobotEnhancedPredictions': None, # DataRobotPredict, 
    'Decision_Tree': None, # DecisionTree, 
    'Predictive Tools\\Forest_Model.yxmc': None, # ForestModel, 
    'Predictive Tools\\Gamma_Regression.yxmc': None, # GammaRegression, 
    'Predictive Tools\\Lift_Chart.yxmc': None, # LiftChart, 
    'Linear Regression': None, # LinearRegression, 
    'Logistic_Regression': None, # LogisticRegression, 
    'Model Coefficients.yxmc': None, # ModelCoefficients, 
    'Predictive Tools\\Model Comparison.yxmc': None, # ModelComparison, 
    'Predictive Tools\\Naive_Bayes.yxmc': None, # NaiveBayesClassifier, 
    'Predictive Tools\\Nested_Test.yxmc': None, # NestedTest, 
    'Predictive Tools\\NetworkViz.yxmc': None, # NetworkAnalysis, 
    'Predictive Tools\\Neural_Network.yxmc': None, # NeuralNetwork, 
    'Score': None, # Score, 
    'Predictive Tools\\Spline_Model.yxmc': None, # SplineModel, 
    'Predictive Tools\\Stepwise.yxmc': None, # Stepwise, 
    'Predictive Tools\\SVM_v2.yxmc': None, # SupportVectorMachine, 
    'Survival Analysis.yxmc': None, # SurvivalAnalysis, 
    'Survival Score.yxmc': None, # SurvivalScore, 
    'Predictive Tools\\Test_of_Means.yxmc': None, # TestofMeans, 
    'Variance Inflation Factors.yxmc': None, # VarianceInflationFactors, 
    'Predictive Tools\\AB_Analysis.yxmc': None, # ABAnalysis, 
    'Predictive Tools\\AB_Controls.yxmc': None, # ABControls, 
    'Predictive Tools\\AB_Treatments.yxmc': None, # ABTreatments, 
    'Predictive Tools\\AB_Trend.yxmc': None, # ABTrend, 
    'Predictive Tools\\ARIMA.yxmc': None, # ARIMA, 
    'Predictive Tools\\ETS.yxmc': None, # ETS, 
    'Predictive Tools\\TS_Compare.yxmc': None, # TSCompare, 
    'Predictive Tools\\TS_Covariate_Forecast.yxmc': None, # TSCovariateForecast, 
    'Predictive Tools\\TimeSeriesFiller.yxmc': None, # TSFiller, 
    'Predictive Tools\\TS_Forecast.yxmc': None, # TSForecast, 
    'TS Forecast Factory.yxmc': None, # TSForecastFactory, 
    'TS Model Factory.yxmc': None, # TSModelFactory, 
    'Predictive Tools\\TS_Plot.yxmc': None, # TSPlot, 
    'Predictive Tools\\Append_Cluster.yxmc': None, # AppendCluster, 
    'Predictive Tools\\Find_Nearest_Neighbors.yxmc': None, # FindNearestNeighbors, 
    'Predictive Tools\\K-Centroids_Cluster_Analysis.yxmc': None, # KCentroidsClusterAnalysis, 
    'Predictive Tools\\K-Centroids_Diagnostics.yxmc': None, # KCentroidsDiagnostics, 
    'Predictive Tools\\MB_Affinity.yxmc': None, # MBAffinity, 
    'Predictive Tools\\MB_Inspect.yxmc': None, # MBInspect, 
    'Predictive Tools\\MB_Rules.yxmc': None, # MBRules, 
    'Multidimensional Scaling.yxmc': None, # MultidimensionalScaling, 
    'Predictive Tools\\Principal_Components.yxmc': None, # PrincipalComponents, 
    'Optimization': None, # Optimization, 
    'SimSampling': None, # SimulationSampling, 
    'SimScoring': None, # SimulationScoring, 
    'SimSummary': None, # SimulationSummary, 
    'azure_data_lake_input': None, # MicrosoftAzureDataLakeFileInput, 
    'azure_data_lake_output': None, # MicrosoftAzureDataLakeFileOutput, 
    'AdobeAnalytics_v3.0.0': None, # AdobeAnalytics, 
    'lteryxConnectorGui.AmazonS3Download.AmazonS3Download': None, # AmazonS3Download, 
    'AlteryxConnectorGui.AmazonS3Upload.AmazonS3Upload': None, # AmazonS3Upload, 
    'AnaplanInput_1_1_0': None, # AnaplanInput, 
    'AnaplanOutput_1_1_0': None, # AnaplanOutput, 
    'AutomationAnywhere360_v1.0.0': None, # AutomationAnywhere, 
    'BoxInput': None, # BoxInput, 
    'BoxOutput': None, # BoxOutput, 
    'CognitiveServicesTextAnalytics': None, # CognitiveServicesTextAnalytics, 
    'DataverseInput_v1.1.1': None, # DataverseInput, 
    'DataverseOutput_v1.1.1': None, # DataverseOutput, 
    'DropboxInput_v1.1.2': None, # DropboxInput, 
    'DropboxOutput_v1.1.2': None, # DropboxOutput, 
    'dynamics_crm_input_v1.0.2': None, # DynamicsCRMInput, 
    'dynamics_crm_output_v1.0.2': None, # DynamicsCRMOutput, 
    'GoogleAnalytics_v8.0.0': None, # GoogleAnalytics, 
    'GoogleAnalytics4Input_1_1_0': None, # GoogleAnalytics4Input, 
    'big_query_input_v3.0.0': None, # GoogleBigQueryInput, 
    'big_query_output_v3.0.0': None, # GoogleBigQueryOutput, 
    'GoogleDriveInput': None, # GoogleDriveInput, 
    'GoogleDriveOutput': None, # GoogleDriveOutput, 
    'google-sheets-input': None, # GoogleSheetsInput, 
    'google-sheets-output': None, # GoogleSheetsOutput, 
    'marketo-append': None, # MarketoAppend, 
    'marketo-input': None, # MarketoInput, 
    'marketo-output': None, # MarketoOutput, 
    'PowerBIOutput': None, # MicrosoftPowerBIOutput, 
    'AlteryxConnectorGui.MongoInput.MongoInput': None, # MongoDBInput, 
    'AlteryxConnectorGui.MongoOutput.MongoOutput': None, # MongoDBOutput, 
    'OneDriveInput': None, # OneDriveInput, 
    'OneDriveOutput': None, # OneDriveOutput, 
    'Outlook365Input_v1.1.0': None, # Outlook365Input, 
    'PowerAutomate_v1.0.1': None, # PowerAutomate, 
    'PublishToTableauServer_v2.0.0': None, # PublishtoTableauServer, 
    'SalesforceInput_v4.2.4': None, # SalesforceInput, 
    'SalesforceOutput_v1.3.1': None, # SalesforceOutput, 
    'ServiceNowInput_1_1_0': None, # ServiceNowInput, 
    'SharePointInput_2_4_0': None, # SharePointInput, 
    'SharePointOutput_2_4_0': None, # SharePointOutput, 
    'AlteryxConnectorDotNet.SharepointInput.SharepointInput': None, # SharePointListInput, 
    'AlteryxConnectorDotNet.SharepointOutput.SharepointOutput': None, # SharePointListOutput, 
    'TableauOutput_1_4_0': None, # TableauOutput, 
    'AlteryxCASSGui.CASS.CASS': None, # CASS, 
    'AlteryxCASSGui.CASSParse.CASSParse': None, # ParseAddress, 
    'ReverseGeocoder.yxmc': None, # ReverseGeocoder, 
    'PortfolioPluginsGui.Geocoder.Geocoder': None, # StreetGeocoder, 
    'PortfolioExplorer.yxmc': None, # USGeocoder, 
    'AlteryxCASSGui.ZIP9Coder.ZIP9Coder': None, # USZIP9Coder, 
    'PortfolioPluginsGui.AllocateAppend.AllocateAppend': None, # AllocateAppend, 
    'PortfolioPluginsGui.AllocateInput.AllocateInput': None, # AllocateInput, 
    'PortfolioPluginsGui.AllocateMetaInfo.AllocateMetaInfo': None, # AllocateMetainfo, 
    'PortfolioPluginsGui.AllocateReport.AllocateReport': None, # AllocateReport, 
    'PortfolioPluginsGui.SolocastMetaInfo.SolocastMetaInfo': None, # BehaviorMetainfo, 
    'PortfolioPluginsGui.SolocastClusterNum.SolocastClusterNum': None, # ClusterCode, 
    'PortfolioPluginsGui.SolocastCompare.SolocastCompare': None, # CompareBehavior, 
    'PortfolioPluginsGui.SolocastCreateProfile.SolocastCreateProfile': None, # CreateProfile, 
    'PortfolioPluginsGui.SolocastDetailAsFields.SolocastDetailAsFields': None, # DetailFields, 
    'Behavior_ProfileComparisonReport.yxmc': None, # ProfileComparisonReport, 
    'Macros\\Behavior_ProfileDetailReport.yxmc': None, # ProfileDetailReport, 
    'PortfolioPluginsGui.SolocastReadProfileSet.SolocastReadProfileSet': None, # ProfileInput, 
    'PortfolioPluginsGui.SolocastWriteProfileSet.SolocastWriteProfileSet': None, # ProfileOutput, 
    'Behavior_ProfileRankReport.yxmc': None, # ProfileRankReport, 
    'CalgaryPluginsGui.CalgaryInput.CalgaryInput': None, # CalgaryInput, 
    'CalgaryPluginsGui.CalgaryJoin.CalgaryJoin': None, # CalgaryJoin, 
    'CalgaryLoadersGui.CalgaryLoader.CalgaryLoader': None, # CalgaryCrossCount, 
    'CalgaryPluginsGui.CalgaryCrossCount.CalgaryCrossCount': None, # CalgaryCrossCountAppend, 
    'CalgaryPluginsGui.CalgaryCrossCountAppend.CalgaryCrossCountAppend': None, # CalgaryLoader, 
    'Custom Spark': None, # ApacheSparkCode, 
    'AlteryxBasePluginsGui.APIOutput.APIOutput': None, # APIOutput, 
    'Base64_Encoder.yxmc': None, # Base64Encoder, 
    'AlteryxBasePluginsGui.BlobConvert.BlobConvert': None, # BlobConvert, 
    'AlteryxBasePluginsGui.BlobInput.BlobInput': None, # BlobInput, 
    'AlteryxBasePluginsGui.BlobOutput.BlobOutput': None, # BlobOutput, 
    'AlteryxBasePluginsGui.BlockUntilDone.BlockUntilDone': None, # BlockUntilDone, 
    'AlteryxGuiToolkit.ControlContainer.ControlContainer': None, # ControlContainer, 
    'AlteryxBasePluginsGui.Detour.Detour': None, # Detour, 
    'AlteryxBasePluginsGui.DetourEnd.DetourEnd': None, # DetourEnd, 
    'AlteryxConnectorGui.Download.Download': None, # Download, 
    'AlteryxBasePluginsGui.DynamicInput.DynamicInput': None, # DynamicInput, 
    'AlteryxBasePluginsGui.DynamicRename.DynamicRename': None, # DynamicRename, 
    'AlteryxBasePluginsGui.DynamicReplace.DynamicReplace': None, # DynamicReplace, 
    'AlteryxBasePluginsGui.DynamicSelect.DynamicSelect': None, # DynamicSelect, 
    'ExpectEqual.yxmc': None, # ExpectEqual, 
    'AlteryxBasePluginsGui.FieldInfo.FieldInfo': None, # FieldInfo, 
    'GitHubCommit.yxmc': None, # GitHubCommit, 
    'GetLastCommit.yxmc': None, # GitHubGetLastCommit, 
    'AlteryxBasePluginsGui.JSONParse.JSONParse': None, # JSONParse, 
    'LicenseAPITool_1_0': None, # LicenseAPI, 
    'AlteryxBasePluginsGui.Message.Message': None, # Message, 
    'JupyterCode': None, # Python, 
    'AlteryxRPluginGui.R': None, # R, 
    'AlteryxBasePluginsGui.RunCommand.RunCommand': None, # RunCommand, 
    'CReW_Runner\\CReW_Runner.yxmc': None, # Runner, 
    'ServerAPI_1_0': None, # ServerAPI, 
    'AlteryxBasePluginsGui.Test.Test': None, # Test, 
    'AlteryxBasePluginsGui.Throttle.Throttle': None, # Throttle, 
    'ConnectTools.ConnectJSONBuilder': None, # ConnectJSONBuilder, 
    'ConnectTools.ConnectOutput': None, # ConnectOutput, 
    'AlteryxBasePluginsGui.JSONBuild.JSONBuild': None, # JSONBuild, 
    'JupyterFlow': None, # JupyterFlow, 
    'KeyValuePairExtraction': None, # KeyValuePairExtraction, 
    'LockInGui.LockInTranspose.LockInTranspose': None, # TransposeInDB, 
    'VisualLayout': None, # VisualLayout, 
    'Modeling': None, # AssistedModeling, 
    'AutoML': None, # AutoML, 
    'BuildFeatures': None, # BuildFeatures, 
    'Classification': None, # Classification, 
    'DataHealth': None, # DataHealth, 
    'FeatureTypes': None, # FeatureTypes, 
    'Fit': None, # Fit, 
    'CloudMLPredict': None, # MachineLearningPredict, 
    'CloudMLUpload': None, # MachineLearningSend, 
    'Predict': None, # Predict, 
    'Regression': None, # Regression, 
    'Transformation': None, # Transformation, 
    'HtmlGuiSdk': None, # HTMLGUILibrary, 
    'NamedEntityRecognition': None, # NamedEntityRecognition, 
    'PartOfSpeechTagger': None, # PartofSpeechTagger, 
    'Sentiment': None, # SentimentAnalysis, 
    'TextClassification': None, # TextClassification, 
    'TextPreProcessing': None, # TextPreprocessing, 
    'TextSummary': None, # TextSummary, 
    'TopicModel': None, # TopicModeling, 
    'WordCloud': None, # WordCloud, 
    'ZeroShotTextClassification': None, # ZeroshotTextClassification, 
    'Barcode': None, # Barcode, 
    'PDFInput': None, # ImageInput, 
    'ImageOutput': None, # ImageOutput, 
    'ImageProcessing': None, # ImageProcessing, 
    'ImageProfile': None, # ImageProfile, 
    'ImageRecognition': None, # ImageRecognition, 
    'ImageTemplate': None, # ImageTemplate, 
    'ImageToText': None, # ImagetoText, 
    'PDFToText': None, # PDFtoText, 
    'OdbcLoader_v2': None, # ODBCLoader
}